# Generated by Django 4.2.13 on 2024-07-06 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info_table',
            old_name='numder',
            new_name='number',
        ),
    ]
