# Generated by Django 4.2.13 on 2024-07-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_numder_info_table_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info_table',
            options={'ordering': ['time_create', 'username'], 'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='info_table',
            name='photo',
        ),
        migrations.AlterField(
            model_name='info_table',
            name='email',
            field=models.CharField(max_length=20, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='info_table',
            name='number',
            field=models.CharField(max_length=11, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='info_table',
            name='username',
            field=models.CharField(max_length=20, verbose_name='Имя пользователя'),
        ),
    ]
